'use strict';
const KEY='expedidocs-v1';
const clean=()=>({version:1,shipments:[],destinations:[],carriers:[],drivers:[]});
let db=clean();
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw&&Array.isArray(raw.shipments)&&Array.isArray(raw.destinations)&&Array.isArray(raw.carriers)){db=raw;db.drivers=Array.isArray(raw.drivers)?raw.drivers:[];}}catch(e){console.warn('No se pudo leer almacenamiento',e);}
const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=(v)=>{const t=$('#toast');t.textContent=v;t.style.display='block';clearTimeout(msg.timer);msg.timer=setTimeout(()=>t.style.display='none',3700)};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch(e){msg('Error al guardar: almacenamiento lleno o bloqueado. Exporta una copia.');return false}};
const uuid=()=>globalThis.crypto?.randomUUID?.()||('e'+Date.now()+Math.random().toString(36).slice(2));
const switchTab=(name)=>{document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='historial')renderHistory();if(name==='catalogos')renderCatalogs();if(name==='inicio')renderHome();window.scrollTo(0,0)};
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
const today=()=>{const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)};
const form=$('#shipmentForm');
const reset=()=>{form.reset();$('#driverSelect').value='';$('#editId').value='';form.elements.date.value=today();$('#formTitle').textContent='Nueva expedición';form.elements.origin.value='Zaragoza'};
reset();
const getRecords=()=>[...db.shipments].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.updated||'').localeCompare(a.updated||''));
const rows=(entries)=>entries.length?'<div class="tblwrap"><table><thead><tr><th>Fecha</th><th>Ref.</th><th>Destino</th><th>Vehículo</th><th>Palets</th><th>Acciones</th></tr></thead><tbody>'+entries.map(s=>'<tr><td>'+esc(s.date)+'</td><td><strong>'+esc(s.ref)+'</strong></td><td>'+esc(s.destination)+'</td><td>'+esc(s.tractor)+'</td><td>'+esc(s.pallets)+'</td><td><button class="btn secondary" data-action="print" data-id="'+esc(s.id)+'">Documento</button><button class="btn secondary" data-action="edit" data-id="'+esc(s.id)+'">Editar</button><button class="btn warn" data-action="delete" data-id="'+esc(s.id)+'">Eliminar</button></td></tr>').join('')+'</tbody></table></div>':'<p class="empty">Todavía no hay expediciones.</p>';
function renderHome(){const arr=db.shipments;$('#kTotal').textContent=arr.length;$('#kPalets').textContent=arr.reduce((n,x)=>n+Number(x.pallets||0),0).toLocaleString('es-ES');$('#kToday').textContent=arr.filter(x=>x.date===today()).length;$('#kDest').textContent=new Set(arr.map(x=>x.destination?.trim().toLowerCase()).filter(Boolean)).size;$('#recent').innerHTML=rows(getRecords().slice(0,5))}
function renderHistory(){const q=$('#search').value.toLocaleLowerCase('es');$('#history').innerHTML=rows(getRecords().filter(x=>[x.ref,x.destination,x.carrier,x.tractor,x.trailer,x.date].some(v=>String(v??'').toLocaleLowerCase('es').includes(q))))}
$('#search').addEventListener('input',renderHistory);
function renderOptions(){const s=$('#destinationSelect');s.innerHTML='<option value="">Seleccionar o escribir manualmente</option>'+db.destinations.map(x=>'<option value="'+esc(x.code)+'">'+esc(x.code+' · '+x.name)+'</option>').join('');$('#carriersList').innerHTML=db.carriers.map(x=>'<option value="'+esc(x.name)+'"></option>').join('');$('#driverSelect').innerHTML='<option value="">Seleccionar conductor...</option>'+db.drivers.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('')}
$('#destinationSelect').addEventListener('change',e=>{let d=db.destinations.find(x=>x.code===e.target.value);if(d){$('#destination').value=d.name;$('#address').value=d.address||''}});
$('#driverSelect').addEventListener('change',e=>{let d=db.drivers.find(x=>x.id===e.target.value);if(!d)return;for(let k of ['driver','tractor','trailer','driverId','phone'])form.elements[k].value=d[k==='driver'?'name':k]||''});
$('#carrier').addEventListener('change',e=>{let c=db.carriers.find(x=>x.name.toLowerCase()===e.target.value.toLowerCase());if(c)form.elements.carrierTax.value=c.tax||''});
function renderCatalogs(){renderOptions();$('#driverList').innerHTML=db.drivers.length?'<table><tbody>'+db.drivers.map(d=>'<tr><td>'+esc(d.name)+'</td><td>'+esc(d.tractor)+'</td><td><button class="btn warn" data-cat="drivers" data-id="'+esc(d.id)+'">×</button></td></tr>').join('')+'</tbody></table>':'<p class="muted">Sin conductores añadidos</p>';$('#destList').innerHTML=db.destinations.length?'<table><tbody>'+db.destinations.map(d=>'<tr><td>'+esc(d.code)+'</td><td>'+esc(d.name)+'</td><td><button class="btn warn" data-cat="destinations" data-id="'+esc(d.id)+'">×</button></td></tr>').join('')+'</tbody></table>':'<p class="muted">Sin destinos añadidos</p>';$('#carrierList').innerHTML=db.carriers.length?'<table><tbody>'+db.carriers.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+esc(c.tax)+'</td><td><button class="btn warn" data-cat="carriers" data-id="'+esc(c.id)+'">×</button></td></tr>').join('')+'</tbody></table>':'<p class="muted">Sin transportistas añadidos</p>'}
$('#destForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target;let d=Object.fromEntries(new FormData(f));d.code=d.code.trim();d.name=d.name.trim();if(db.destinations.some(x=>x.code.toLowerCase()===d.code.toLowerCase()))return msg('Código de destino duplicado');d.id=uuid();db.destinations.push(d);if(save()){f.reset();renderCatalogs();msg('Destino añadido')}});
$('#carrierForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target;let d=Object.fromEntries(new FormData(f));d.name=d.name.trim();if(db.carriers.some(x=>x.name.toLowerCase()===d.name.toLowerCase()))return msg('Transportista duplicado');d.id=uuid();db.carriers.push(d);if(save()){f.reset();renderCatalogs();msg('Transportista añadido')}});
$('#driverForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target;let d=Object.fromEntries(new FormData(f));d.name=d.name.trim();if(db.drivers.some(x=>x.name.toLowerCase()===d.name.toLowerCase()&&x.tractor.replace(/\\s/g,'').toLowerCase()===d.tractor.replace(/\\s/g,'').toLowerCase()))return msg('Conductor y tractora ya registrados');d.id=uuid();db.drivers.push(d);if(save()){f.reset();renderCatalogs();msg('Conductor añadido')}});
$('#catalogos').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;if(!confirm('¿Eliminar esta entrada del catálogo? Las expediciones ya guardadas no se alteran.'))return;db[b.dataset.cat]=db[b.dataset.cat].filter(x=>x.id!==b.dataset.id);save();renderCatalogs()});
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;let d=Object.fromEntries(new FormData(form));d.ref=d.ref.trim();d.pallets=Number(d.pallets);d.packages=Number(d.packages||0);d.weight=d.weight===''?'':Number(d.weight);d.tractor=d.tractor.trim().toUpperCase();d.trailer=d.trailer.trim().toUpperCase();if(!d.ref||!d.destination.trim()||!d.sender.trim()||!d.carrier.trim()||!d.tractor)return msg('Revisa los campos obligatorios');if(!Number.isSafeInteger(d.pallets)||d.pallets<0||!Number.isSafeInteger(d.packages)||d.packages<0||d.weight!==''&&(!Number.isFinite(d.weight)||d.weight<0))return msg('Cantidad o peso no válido');if(db.shipments.some(s=>s.ref.toLowerCase()===d.ref.toLowerCase()&&s.id!==d.id))return msg('Ya existe esa referencia; edita su expedición');const old=db.shipments.find(x=>x.id===d.id);d.id=old?.id||uuid();d.created=old?.created||new Date().toISOString();d.updated=new Date().toISOString();db.shipments=old?db.shipments.map(x=>x.id===d.id?d:x):[...db.shipments,d];if(save()){reset();renderHome();switchTab('historial');msg(old?'Expedición actualizada':'Expedición guardada')}});
$('#resetForm').addEventListener('click',reset);$('#newBtn').addEventListener('click',()=>{reset();switchTab('nueva')});
function edit(id){let d=db.shipments.find(x=>x.id===id);if(!d)return;reset();for(let [k,v] of Object.entries(d)){let el=form.elements.namedItem(k);if(el&&typeof v!=='object')el.value=v??''}$('#editId').value=d.id;$('#formTitle').textContent='Editar · '+d.ref;switchTab('nueva')}
const cell=(label,value,cls='')=>'<div class="cell '+cls+'"><label>'+esc(label)+'</label>'+esc(value||'—')+'</div>';
function printDocument(id){const d=db.shipments.find(x=>x.id===id);if(!d)return;$('#printArea').hidden=false;$('#printArea').innerHTML='<article class="paper"><h2>DOCUMENTO DE CONTROL DE TRANSPORTE DE MERCANCÍAS POR CARRETERA</h2><p style="text-align:right;font-size:12px">Referencia: '+esc(d.ref)+' · Fecha: '+esc(d.date)+' '+esc(d.time)+'</p><div class="columns">'+cell('1. Cargador / remitente',d.sender+'\n'+d.senderAddress)+cell('18. Cargador contractual',d.sender)+cell('1 bis. Expedidor',d.dispatcher||d.sender)+cell('19. Transportista efectivo',d.carrier+'\n'+d.carrierTax)+cell('2. Consignatario / destinatario',d.consignee||d.destination)+'<div class="cell"><label>Vehículo y conductor</label>'+esc('Tractora: '+d.tractor+'\nRemolque: '+d.trailer+'\nConductor: '+d.driver+'\nDocumento: '+d.driverId+'\nTeléfono: '+d.phone)+'</div>'+cell('3. Lugar de destino',d.destination+'\n'+d.address)+cell('5. Fecha y lugar de origen',d.date+' '+d.time+'\n'+d.origin)+cell('Mercancía / embalaje',d.goods+'\n'+d.packaging+' · '+d.mode)+cell('Cantidad / peso','Palets: '+d.pallets+'\nBultos: '+d.packages+'\nPeso bruto: '+(d.weight===''?'—':d.weight+' kg')+'\nPrecinto: '+d.seal)+cell('Observaciones',d.notes,'span2')+'<div class="cell sign"><label>Firma y sello del cargador</label></div><div class="cell sign"><label>Fecha y firma del transportista</label></div><div class="cell sign"><label>Recepción y firma del destinatario</label></div><div class="cell sign"><label>Reservas e incidencias en entrega</label></div></div><p style="font-size:10px">Documento generado desde ExpediDocs. Revisar datos y adecuación normativa antes del uso oficial.</p></article>';window.print();setTimeout(()=>{$('#printArea').hidden=true},700)}
document.body.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;let id=b.dataset.id;if(b.dataset.action==='edit')edit(id);if(b.dataset.action==='print')printDocument(id);if(b.dataset.action==='delete'&&confirm('¿Eliminar esta expedición? Esta operación no se puede deshacer salvo mediante una copia de seguridad.')){db.shipments=db.shipments.filter(x=>x.id!==id);if(save()){renderHome();renderHistory();msg('Expedición eliminada')}}});
const download=(content,name,type)=>{let url=URL.createObjectURL(new Blob([content],{type}));let a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500)};
$('#exportBtn').addEventListener('click',()=>download(JSON.stringify({format:'expedidocs-v1',exportedAt:new Date().toISOString(),...db},null,2),'expedidocs-copia-'+today()+'.json','application/json'));
$('#csvBtn').addEventListener('click',()=>{const keys=['ref','date','time','origin','destination','address','sender','consignee','carrier','tractor','trailer','driver','pallets','packages','weight','goods','seal','notes'];const quote=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,'\u0027$&')+'"';download('\ufeff'+[keys.join(';'),...db.shipments.map(s=>keys.map(k=>quote(s[k])).join(';'))].join('\r\n'),'expediciones-'+today()+'.csv','text/csv;charset=utf-8')});
$('#importFile').addEventListener('change',async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>10_000_000)throw Error('Archivo demasiado grande');let x=JSON.parse(await file.text());if(x.format!=='expedidocs-v1'||!Array.isArray(x.shipments)||!Array.isArray(x.destinations)||!Array.isArray(x.carriers)||(x.drivers!==undefined&&!Array.isArray(x.drivers))||x.shipments.some(s=>!s.id||!s.ref||!s.date||!s.destination)||x.shipments.length>100000)throw Error('Formato de copia no válido');if(!confirm('La importación sustituirá TODAS las expediciones y catálogos locales actuales. ¿Continuar?'))return;let prev=db;db={version:1,shipments:x.shipments,destinations:x.destinations,carriers:x.carriers,drivers:x.drivers||[]};if(!save())db=prev;else{renderHome();renderCatalogs();renderHistory();msg('Copia restaurada correctamente')}}catch(err){msg(err.message||'Error al importar')}finally{e.target.value=''}});
$('#wipeBtn').addEventListener('click',()=>{if(prompt('Escribe BORRAR para eliminar expediciones y catálogos locales:')!=='BORRAR')return;let prev=db;db=clean();if(!save())db=prev;else{renderHome();renderCatalogs();renderHistory();reset();msg('Datos locales eliminados')}});
renderHome();renderCatalogs();
