'use strict';
const KEY='expedidocs-v1';
const clean=()=>({version:1,shipments:[],destinations:[],carriers:[],drivers:[],tractors:[],trailers:[]});
let db=clean();
// Expeditions and personal data are not loaded from localStorage. Secure cloud is the source of truth.
const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=(v)=>{const t=$('#toast');t.textContent=v;t.style.display='block';clearTimeout(msg.timer);msg.timer=setTimeout(()=>t.style.display='none',3700)};
const API_URL='https://shrmlnantusaaeqetlkk.supabase.co';
const API_KEY='sb_publishable_nedhbCcWQBE8Nah8AW72FA_3sF3wFsP';
const cloud=window.supabase?.createClient(API_URL,API_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let activeUser=null,writeQueue=Promise.resolve();
const cloudStatus=v=>{$('#cloudStatus').textContent=v};
const save=()=>{if(!activeUser||!cloud){msg('Sin sesión: no se puede guardar');return false}const snapshot=JSON.parse(JSON.stringify(db));cloudStatus('Guardando en nube...');writeQueue=writeQueue.catch(()=>{}).then(async()=>{let {error}=await cloud.from('expedidocs_data').upsert({user_id:activeUser.id,payload:snapshot,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error){cloudStatus('Error de guardado');msg('No se ha podido guardar en la nube. Exporta una copia y revisa la conexión.');throw error}cloudStatus('✓ Guardado en nube')});return true};
async function authReady(session){activeUser=session?.user||null;$('#privateApp').hidden=!activeUser;$('#authGate').hidden=!!activeUser;if(!activeUser){db=clean();return}cloudStatus('Cargando información...');const {data,error}=await cloud.from('expedidocs_data').select('payload').eq('user_id',activeUser.id).maybeSingle();if(error){cloudStatus('Error al recuperar datos');msg('No se pudo cargar la base privada');$('#privateApp').hidden=true;$('#authGate').hidden=false;activeUser=null;return}const p=data?.payload;if(p&&Array.isArray(p.shipments)&&Array.isArray(p.destinations)&&Array.isArray(p.carriers)){db={version:1,shipments:p.shipments,destinations:p.destinations,carriers:p.carriers,drivers:Array.isArray(p.drivers)?p.drivers:[],tractors:Array.isArray(p.tractors)?p.tractors:[],trailers:Array.isArray(p.trailers)?p.trailers:[]}}else db=clean();renderHome();renderCatalogs();renderHistory();cloudStatus('✓ Sesión privada conectada');}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();if(!cloud)return $('#authStatus').textContent='No se ha podido cargar la conexión segura';$('#authStatus').textContent='Comprobando acceso...';const {data,error}=await cloud.auth.signInWithPassword({email:$('#authEmail').value.trim(),password:$('#authPassword').value});if(error)return $('#authStatus').textContent='Acceso incorrecto: '+error.message;$('#authPassword').value='';await authReady(data.session);$('#authStatus').textContent=''});
$('#signUpBtn').addEventListener('click',async()=>{if(!cloud)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<8)return $('#authStatus').textContent='Introduce correo y contraseña de al menos 8 caracteres.';if(!confirm('¿Crear una cuenta privada con este correo? Usa la contraseña inicial indicada y cámbiala después.'))return;const {data,error}=await cloud.auth.signUp({email,password});$('#authStatus').textContent=error?'No se pudo crear: '+error.message:'Cuenta creada. Comprueba tu correo si se solicita confirmación; después pulsa Acceder.';if(data?.session)await authReady(data.session)});
$('#signOutBtn').addEventListener('click',async()=>{await writeQueue.catch(()=>{});await cloud?.auth.signOut();db=clean();activeUser=null;$('#privateApp').hidden=true;$('#authGate').hidden=false;$('#authPassword').value=''});
if(!cloud){$('#authStatus').textContent='No se pudo inicializar el servicio de autenticación';}else cloud.auth.getSession().then(({data})=>authReady(data.session));
const uuid=()=>globalThis.crypto?.randomUUID?.()||('e'+Date.now()+Math.random().toString(36).slice(2));
const switchTab=(name)=>{document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='historial')renderHistory();if(name==='catalogos')renderCatalogs();if(name==='inicio')renderHome();window.scrollTo(0,0)};
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
const today=()=>{const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)};
const form=$('#shipmentForm');
const FIXED_SENDER=Object.freeze({sender:'SERVAL RETAIL Y CONSUMO SL',senderAddress:'CALLE OSCA 10, POLÍGONO PLAZA (ZARAGOZA)',senderTax:'B67872739'});
function enforceSender(){Object.entries(FIXED_SENDER).forEach(([key,value])=>{form.elements[key].value=value;form.elements[key].readOnly=true})}
const reset=()=>{form.reset();$('#driverSelect').value='';$('#editId').value='';form.elements.date.value=today();$('#formTitle').textContent='Nueva expedición';form.elements.origin.value='Zaragoza';form.elements.sender.value='SERVAL RETAIL Y CONSUMO SL';form.elements.senderAddress.value='CALLE OSCA 10, POLÍGONO PLAZA (ZARAGOZA)';form.elements.senderTax.value='B67872739';enforceSender()};
reset();
const getRecords=()=>[...db.shipments].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.updated||'').localeCompare(a.updated||''));
const rows=(entries)=>entries.length?'<div class="tblwrap"><table><thead><tr><th>Fecha</th><th>Ref.</th><th>Destino</th><th>Vehículo</th><th>Palets</th><th>Acciones</th></tr></thead><tbody>'+entries.map(s=>'<tr><td>'+esc(s.date)+'</td><td><strong>'+esc(s.ref)+'</strong></td><td>'+esc(s.destination)+'</td><td>'+esc(s.tractor)+'</td><td>'+esc(s.pallets)+'</td><td><button class="btn secondary" data-action="print" data-id="'+esc(s.id)+'">Documento</button><button class="btn secondary" data-action="edit" data-id="'+esc(s.id)+'">Editar</button><button class="btn warn" data-action="delete" data-id="'+esc(s.id)+'">Eliminar</button></td></tr>').join('')+'</tbody></table></div>':'<p class="empty">Todavía no hay expediciones.</p>';
function renderHome(){const arr=db.shipments;$('#kTotal').textContent=arr.length;$('#kPalets').textContent=arr.reduce((n,x)=>n+Number(x.pallets||0),0).toLocaleString('es-ES');$('#kToday').textContent=arr.filter(x=>x.date===today()).length;$('#kDest').textContent=new Set(arr.map(x=>x.destination?.trim().toLowerCase()).filter(Boolean)).size;$('#recent').innerHTML=rows(getRecords().slice(0,5))}
function renderHistory(){const q=$('#search').value.toLocaleLowerCase('es');$('#history').innerHTML=rows(getRecords().filter(x=>[x.ref,x.destination,x.carrier,x.tractor,x.trailer,x.date].some(v=>String(v??'').toLocaleLowerCase('es').includes(q))))}
$('#search').addEventListener('input',renderHistory);
function renderOptions(){const s=$('#destinationSelect');s.innerHTML='<option value="">Seleccionar o escribir manualmente</option>'+db.destinations.map(x=>'<option value="'+esc(x.code)+'">'+esc(x.code+' · '+x.name)+'</option>').join('');$('#carriersList').innerHTML=db.carriers.map(x=>'<option value="'+esc(x.name)+'"></option>').join('');$('#driverSelect').innerHTML='<option value="">Seleccionar conductor...</option>'+db.drivers.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('')}
$('#destinationSelect').addEventListener('change',e=>{let d=db.destinations.find(x=>x.code===e.target.value);if(d){$('#destination').value=d.name;$('#address').value=d.address||''}});
$('#driverSelect').addEventListener('change',e=>{let d=db.drivers.find(x=>x.id===e.target.value);if(!d)return;for(let k of ['driver','driverId','phone'])form.elements[k].value=d[k==='driver'?'name':k]||''});
$('#carrier').addEventListener('change',e=>{let c=db.carriers.find(x=>x.name.toLowerCase()===e.target.value.toLowerCase());if(c)form.elements.carrierTax.value=c.tax||''});
function renderCatalogs(){renderOptions();$('#driverList').innerHTML=db.drivers.length?'<table><tbody>'+db.drivers.map(d=>'<tr><td>'+esc(d.name)+'</td><td>'+esc(d.tractor)+'</td><td><button class="btn warn" data-cat="drivers" data-id="'+esc(d.id)+'">×</button></td></tr>').join('')+'</tbody></table>':'<p class="muted">Sin conductores añadidos</p>';$('#destList').innerHTML=db.destinations.length?'<table><tbody>'+db.destinations.map(d=>'<tr><td>'+esc(d.code)+'</td><td>'+esc(d.name)+'</td><td><button class="btn warn" data-cat="destinations" data-id="'+esc(d.id)+'">×</button></td></tr>').join('')+'</tbody></table>':'<p class="muted">Sin destinos añadidos</p>';$('#carrierList').innerHTML=db.carriers.length?'<table><tbody>'+db.carriers.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+esc(c.tax)+'</td><td><button class="btn warn" data-cat="carriers" data-id="'+esc(c.id)+'">×</button></td></tr>').join('')+'</tbody></table>':'<p class="muted">Sin transportistas añadidos</p>'}
$('#destForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target;let d=Object.fromEntries(new FormData(f));d.code=d.code.trim();d.name=d.name.trim();if(db.destinations.some(x=>x.code.toLowerCase()===d.code.toLowerCase()))return msg('Código de destino duplicado');d.id=uuid();db.destinations.push(d);if(save()){f.reset();renderCatalogs();msg('Destino añadido')}});
$('#carrierForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target;let d=Object.fromEntries(new FormData(f));d.name=d.name.trim();if(db.carriers.some(x=>x.name.toLowerCase()===d.name.toLowerCase()))return msg('Transportista duplicado');d.id=uuid();db.carriers.push(d);if(save()){f.reset();renderCatalogs();msg('Transportista añadido')}});
$('#driverForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target;let d=Object.fromEntries(new FormData(f));d.name=d.name.trim();if(db.drivers.some(x=>x.name.toLowerCase()===d.name.toLowerCase()&&x.driverId===d.driverId))return msg('Conductor y tractora ya registrados');d.id=uuid();db.drivers.push(d);if(save()){f.reset();renderCatalogs();msg('Conductor añadido')}});
$('#catalogos').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;if(!confirm('¿Eliminar esta entrada del catálogo? Las expediciones ya guardadas no se alteran.'))return;db[b.dataset.cat]=db[b.dataset.cat].filter(x=>x.id!==b.dataset.id);save();renderCatalogs()});
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;let d={...Object.fromEntries(new FormData(form)),...FIXED_SENDER};d.ref=d.ref.trim();d.pallets=Number(d.pallets);d.packages=Number(d.packages||0);d.bars=Number(d.bars||0);d.weight=d.weight===''?'':Number(d.weight);d.tractor=d.tractor.trim().toUpperCase();d.trailer=d.trailer.trim().toUpperCase();if(!d.ref||!d.destination.trim()||!d.sender.trim()||!d.carrier.trim()||!d.tractor)return msg('Revisa los campos obligatorios');if(!Number.isSafeInteger(d.pallets)||d.pallets<0||!Number.isSafeInteger(d.packages)||d.packages<0||d.weight!==''&&(!Number.isFinite(d.weight)||d.weight<0))return msg('Cantidad o peso no válido');if(db.shipments.some(s=>s.ref.toLowerCase()===d.ref.toLowerCase()&&s.id!==d.id))return msg('Ya existe esa referencia; edita su expedición');const old=db.shipments.find(x=>x.id===d.id);d.id=old?.id||uuid();d.created=old?.created||new Date().toISOString();d.updated=new Date().toISOString();db.shipments=old?db.shipments.map(x=>x.id===d.id?d:x):[...db.shipments,d];if(save()){reset();renderHome();switchTab('historial');msg(old?'Expedición actualizada':'Expedición guardada')}});
$('#resetForm').addEventListener('click',reset);$('#newBtn').addEventListener('click',()=>{reset();switchTab('nueva')});
function edit(id){let d=db.shipments.find(x=>x.id===id);if(!d)return;reset();for(let [k,v] of Object.entries(d)){let el=form.elements.namedItem(k);if(el&&typeof v!=='object')el.value=v??''}enforceSender();$('#editId').value=d.id;$('#formTitle').textContent='Editar · '+d.ref;switchTab('nueva')}
const cell=(label,value,cls='')=>'<div class="cell '+cls+'"><label>'+esc(label)+'</label>'+esc(value||'—')+'</div>';
const docBox=(label,value,extra='')=>'<div class="cmr-box '+extra+'"><small>'+esc(label)+'</small><div class="cmr-value">'+esc(value||'—')+'</div></div>';
function documentPage(d,copy,i){
const dt=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'}):'—';
const sender=[d.sender,d.senderTax?('CIF '+d.senderTax):'',d.senderAddress].filter(Boolean).join('\n');
Object.assign(d,FIXED_SENDER);return '<article class="cmr-page"><h2>DOCUMENTO DE CONTROL DE TRANSPORTE DE MERCANCÍAS POR CARRETERA</h2>'+
'<div class="cmr-main"><div class="cmr-left">'+
docBox('1. Cargador o remitente (nombre o denominación social y domicilio)',sender,'tall')+
docBox('1 bis. Expedidor, si no coincide con el cargador',d.dispatcher,'short')+
docBox('2. Consignatario o destinatario (nombre y domicilio)',(d.consignee||d.destination)+'\n'+d.address,'tall')+
docBox('3. Lugar de destino de la expedición',d.destination,'short')+
docBox('5. Fecha y lugar de origen de la expedición',dt(d.date)+' · '+(d.time||'')+'\n'+d.origin,'short')+
'</div><div class="cmr-right">'+
docBox('Información reglamentaria','Documento de control administrativo del transporte público de mercancías por carretera.','short')+
docBox('18. Cargador contractual',sender,'tall')+
docBox('19. Transportista efectivo',d.carrier+'\n'+(d.carrierTax||''),'tall')+
docBox('19 bis. Transportistas efectivos sucesivos','','short')+
docBox('20. Reservas y observaciones',d.notes,'tall')+
'</div></div>'+
'<div class="cmr-mid"><div><div class="goods-grid">'+
docBox('6. Marcas o identificación de los bultos',d.goods)+docBox('7. Nº de bultos',d.packages)+docBox('8. Clase de embalaje',d.packaging)+docBox('9. Naturaleza de la mercancía',d.mode)+
'</div><table class="cmr-quantity"><tbody><tr><th>PALETS MADERA ENVIADOS</th><td>'+esc(d.packaging)+'</td></tr><tr><th>NÚMERO (BASES DE PALETS) ENVIADOS</th><td><strong>'+esc(d.pallets)+'</strong></td></tr><tr><th>NÚMERO DE BURRAS</th><td>'+esc(d.bars||0)+'</td></tr></tbody></table>'+
'<div class="cmr-summary"><div>PALES <strong>'+esc(d.pallets)+'</strong></div><div>PESO CARGA <strong>'+esc(d.weight===''?'—':d.weight+' Kg.')+'</strong></div><div>PRECINTO <strong>'+esc(d.seal||'—')+'</strong></div></div></div>'+
'<div><small>12 bis. Vehículo utilizado durante la operación de transporte</small><table class="cmr-vehicle"><tbody><tr><th>TRACTORA</th><th>REMOLQUE</th></tr><tr><td>'+esc(d.tractor)+'</td><td>'+esc(d.trailer)+'</td></tr><tr><th>NOMBRE</th><td>'+esc(d.driver)+'</td></tr><tr><th>DNI / NIE</th><td>'+esc(d.driverId)+'</td></tr><tr><th>TELÉFONO</th><td>'+esc(d.phone)+'</td></tr></tbody></table><div class="cmr-model"><strong>MODELO</strong><div>'+esc(d.model||'—')+'</div></div></div></div>'+
'<div class="cmr-bottom"><div>'+docBox('Vehículo y precinto','TRACTORA: '+d.tractor+'  ·  REMOLQUE: '+d.trailer+'\nPRECINTO: '+(d.seal||'—'))+docBox('13. Precio del transporte (si procede)','')+docBox('16. Referencia a contrato de transporte, si procede',d.ref)+'</div><div>'+docBox('DÍA DE DESCARGA',dt(d.unloadDate||d.date))+docBox('14. Instrucciones del cargador',d.notes)+docBox('15. Estipulaciones particulares de carga y descarga','')+'</div></div>'+
'<h3 class="cmr-copy">'+esc(i)+'.- EJEMPLAR PARA EL '+esc(copy.toUpperCase())+'</h3>'+
'<div class="cmr-sign"><div>17. Firma y sello del cargador</div><div>18. Fecha y firma del transportista<br>'+esc(dt(d.date)+' '+(d.time||''))+'</div><div>21. Recibo de mercancía y firma/sello del consignatario<br>HORA LLEGADA: __________ <br>HORA SALIDA: __________</div></div>'+
'<footer>Referencia: '+esc(d.ref)+' · '+esc(copy)+' · Copia '+i+' de 4. Documento generado desde ExpediDocs; comprobar los datos antes de su uso.</footer></article>';
}
function printDocument(id){const d=db.shipments.find(x=>x.id===id);if(!d)return;$('#printArea').hidden=false;$('#printArea').innerHTML=['cargador','transportista','destinatario','archivo / control'].map((c,i)=>documentPage(d,c,i+1)).join('');const finish=()=>{$('#printArea').hidden=true;window.removeEventListener('afterprint',finish)};window.addEventListener('afterprint',finish);window.print();}
document.body.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;let id=b.dataset.id;if(b.dataset.action==='edit')edit(id);if(b.dataset.action==='print')printDocument(id);if(b.dataset.action==='delete'&&confirm('¿Eliminar esta expedición? Esta operación no se puede deshacer salvo mediante una copia de seguridad.')){db.shipments=db.shipments.filter(x=>x.id!==id);if(save()){renderHome();renderHistory();msg('Expedición eliminada')}}});
const download=(content,name,type)=>{let url=URL.createObjectURL(new Blob([content],{type}));let a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500)};
$('#exportBtn').addEventListener('click',()=>download(JSON.stringify({format:'expedidocs-v1',exportedAt:new Date().toISOString(),...db},null,2),'expedidocs-copia-'+today()+'.json','application/json'));
$('#csvBtn').addEventListener('click',()=>{const keys=['ref','date','time','origin','destination','address','sender','consignee','carrier','tractor','trailer','driver','pallets','packages','weight','goods','seal','notes'];const quote=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,'\u0027$&')+'"';download('\ufeff'+[keys.join(';'),...db.shipments.map(s=>keys.map(k=>quote(s[k])).join(';'))].join('\r\n'),'expediciones-'+today()+'.csv','text/csv;charset=utf-8')});
$('#importFile').addEventListener('change',async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>10_000_000)throw Error('Archivo demasiado grande');let x=JSON.parse(await file.text());if(x.format!=='expedidocs-v1'||!Array.isArray(x.shipments)||!Array.isArray(x.destinations)||!Array.isArray(x.carriers)||(x.drivers!==undefined&&!Array.isArray(x.drivers))||x.shipments.some(s=>!s.id||!s.ref||!s.date||!s.destination)||x.shipments.length>100000)throw Error('Formato de copia no válido');if(!confirm('La importación sustituirá TODAS las expediciones y catálogos locales actuales. ¿Continuar?'))return;let prev=db;db={version:1,shipments:x.shipments,destinations:x.destinations,carriers:x.carriers,drivers:x.drivers||[],tractors:x.tractors||[],trailers:x.trailers||[]};if(!save())db=prev;else{renderHome();renderCatalogs();renderHistory();msg('Copia restaurada correctamente')}}catch(err){msg(err.message||'Error al importar')}finally{e.target.value=''}});
$('#wipeBtn').addEventListener('click',()=>{if(prompt('Escribe BORRAR para eliminar expediciones y catálogos locales:')!=='BORRAR')return;let prev=db;db=clean();if(!save())db=prev;else{renderHome();renderCatalogs();renderHistory();reset();msg('Datos locales eliminados')}});
renderHome();renderCatalogs();
